### ISSUE TITLE
Add an "update location" endpoint on the Broadcast service

### ISSUE THREAD

**Issue by Minibrams** [sea-shanty-2/gateway#9]
The client will request a location update when they have moved for enough from their last known position (their position in the cluster map). 

This endpoint is to be called by the client with an updated location. The endpoint should simply propagate the broadcasting client object to the `data/update` endpoint in the clustering component.

**Comment by theisjendal** [comment]
The client now updates their position. Still need to propagate the object to `data/update`.

**Comment by Minibrams** [comment]
@tj45794 This endpoint exists.

**Comment by mjarlund** [comment]
Was fixed in commit f5ee58a4234d684fc567f89798e069081ec051a4
